
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 17;
  public static final int LT = 8;
  public static final int IDENT = 26;
  public static final int ELSE = 4;
  public static final int PLUS = 13;
  public static final int RBRACE = 25;
  public static final int RPAREN = 23;
  public static final int OR = 18;
  public static final int LTE = 10;
  public static final int SEMI = 20;
  public static final int WHILE = 5;
  public static final int STAR = 15;
  public static final int SLASH = 16;
  public static final int NOT = 21;
  public static final int IF = 3;
  public static final int LBRACE = 24;
  public static final int LPAREN = 22;
  public static final int GT = 9;
  public static final int GTE = 11;
  public static final int VISUALIZAR = 6;
  public static final int NUMBER = 27;
  public static final int EOF = 0;
  public static final int INT_KW = 2;
  public static final int MINUS = 14;
  public static final int error = 1;
  public static final int ASSIGN = 19;
  public static final int EQEQ = 12;
  public static final int NEQ = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT_KW",
  "IF",
  "ELSE",
  "WHILE",
  "VISUALIZAR",
  "NEQ",
  "LT",
  "GT",
  "LTE",
  "GTE",
  "EQEQ",
  "PLUS",
  "MINUS",
  "STAR",
  "SLASH",
  "AND",
  "OR",
  "ASSIGN",
  "SEMI",
  "NOT",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "IDENT",
  "NUMBER"
  };
}

